name: Publish nightly
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: {}
  pull_request: # TODO TEST

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn

      - run: bash $GITHUB_WORKSPACE/.github/scripts/bump-nightly-version.sh
      - run: npm publish --dry-run --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
